const axios = require('axios');

const SYSTEM_INSTRUCTION = `You are the NoobSyte Learning Assistant, an AI tutor embedded inside the NoobSyte online learning platform, which teaches Java programming and Data Structures & Algorithms (DSA).

Your job has two parts:

1. TUTORING — Answer conceptual questions about Java and DSA topics (variables, OOP, collections, recursion, sorting, trees, graphs, dynamic programming, etc.) clearly and at a beginner-to-intermediate level. Assume the learner is a student, not an expert.

2. DEBUGGING — When a learner pastes code, help them find and understand the bug rather than just rewriting it for them. Explain *why* it's wrong before showing *how* to fix it.

Guidelines:
- Keep answers concise and focused — prefer short explanations with a small code example over long essays.
- Use simple, encouraging language. Avoid jargon without explaining it the first time you use it.
- Always format code in fenced code blocks with the correct language tag.
- If a question is ambiguous, ask one clarifying question instead of guessing.
- If asked something completely unrelated to programming or this platform's content (e.g. general trivia, personal advice), politely redirect the learner back to Java/DSA topics.
- Never claim to run or execute code yourself — you can explain expected behavior, but the platform's own compiler feature is what actually runs code.
- Do not make up APIs, methods, or language features that don't exist — if unsure, say so.`;

/**
 * Proxies chat requests to Gemini Flash with system tutoring instructions
 * @route POST /api/v1/tutor/chat
 */
const askTutor = async (req, res) => {
  try {
    const { message, history } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.status(500).json({
        success: false,
        message: 'Gemini API key is not configured on the backend server.'
      });
    }

    if (!message) {
      return res.status(400).json({
        success: false,
        message: 'Message field is required.'
      });
    }

    // Format chat contents for Gemini API (user role & model role)
    const contents = [];
    if (history && Array.isArray(history)) {
      history.forEach(item => {
        if (item.role && item.parts && Array.isArray(item.parts)) {
          contents.push({
            role: item.role === 'model' ? 'model' : 'user',
            parts: item.parts.map(p => ({ text: p.text || '' }))
          });
        }
      });
    }

    // Add current user prompt
    contents.push({
      role: 'user',
      parts: [{ text: message }]
    });

    const requestBody = {
      contents,
      systemInstruction: {
        parts: [{ text: SYSTEM_INSTRUCTION }]
      }
    };

    // Call Google's Gemini Flash generateContent endpoint with fallback routing and timeouts
    let response;
    try {
      response = await axios.post(
        'https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent',
        requestBody,
        {
          headers: {
            'Content-Type': 'application/json',
            'X-goog-api-key': apiKey
          },
          timeout: 8000 // 8-second timeout for primary model
        }
      );
    } catch (primaryError) {
      console.warn("⚠️ gemini-flash-latest timed out, returned error, or high demand. Falling back to gemini-3.1-flash-lite...");
      response = await axios.post(
        'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent',
        requestBody,
        {
          headers: {
            'Content-Type': 'application/json',
            'X-goog-api-key': apiKey
          },
          timeout: 10000 // 10-second timeout for fallback model
        }
      );
    }

    const candidates = response.data.candidates;
    if (!candidates || candidates.length === 0 || !candidates[0].content || !candidates[0].content.parts || candidates[0].content.parts.length === 0) {
      return res.status(502).json({
        success: false,
        message: 'No response candidates generated by Gemini API.'
      });
    }

    const reply = candidates[0].content.parts[0].text;

    return res.status(200).json({
      success: true,
      data: {
        reply
      }
    });
  } catch (error) {
    console.error('Gemini API request failed:', error.response?.data || error.message);
    return res.status(error.response?.status || 500).json({
      success: false,
      message: error.response?.data?.error?.message || error.message || 'AI tutoring service failed.'
    });
  }
};

module.exports = {
  askTutor
};
